apiVersion: v1
kind: Service
metadata:
  name: rappidu-application-service
spec:
  type: LoadBalancer
  selector:
    app: rappidu-application
  ports:
  - protocol: TCP
    port: 80 # Porta externa
    targetPort: 8080 # Porta onde o container está escutando