name: Deploy Rappidu AWS - EKS

on:
  push:
    branches:
      - main

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "EKS-RAPPIDU"

jobs:
  deploy:
    name: Deploy AWS
    runs-on: ubuntu-latest
    environment:
      name: aws-lab-fiap
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{env.REGION_DEFAULT}}

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{env.CLUSTER_NAME}} --region ${{env.REGION_DEFAULT}}

      - name: Kube Apply
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/svc.yaml
